# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  # Trigger pipeline on commits to main branch
- main

variables:
  # Ubuntu-latest image is used for building and deploying the app
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build_Test
  displayName: Build & Test project
  jobs:
  - job: Build # Build the app and run tests
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: Docker@2 # Build and push image to Docker Hub
        inputs:
          containerRegistry: 'dockerRegistryServiceConnection'
          repository: 'nkiboi/aks-store-demo'
          command: 'buildAndPush'
          Dockerfile: 'order-service/Dockerfile'
          buildContext: 'src/order-service'